import { defineConfig } from '@arvin-studio/eslint-config';

export default defineConfig([
  {
    rules: {
      'vue/multi-word-component-names': 'off',
      'vue/one-component-per-file': 'off',
      'vue/require-default-prop': 'off',
      'unicorn/name-replacements': 'off',
      'unicorn/no-computed-property-existence-check': 'off',
      'unicorn/prefer-default-parameters': 'off',
      'unicorn/no-top-level-assignment-in-function': 'off',
      'unicorn/no-top-level-side-effects': 'off',
      'unicorn/no-for-each': 'off',
      'unicorn/prefer-smaller-scope': 'off',
      'unicorn/prefer-simple-condition-first': 'off',
      '@typescript-eslint/unified-signatures': 'off',
      'no-restricted-properties': 'off',
      'unicorn/consistent-boolean-name': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/no-unsafe-string-replacement': 'off',
      'unicorn/no-nested-ternary': 'off',
      'unicorn/no-declarations-before-early-exit': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unicorn/prefer-number-coercion': 'off',
      'prefer-const': 'off',
      'unicorn/no-unsafe-property-key': 'off',
      'unicorn/consistent-compound-words': 'off',
      'prefer-spread': 'off',
      '@typescript-eslint/no-dynamic-delete': 'off',
      'unicorn/no-useless-else': 'off',
      'unicorn/no-uncalled-method': 'off',
      'unicorn/no-new-array': 'off',
    },
  },
]);
