import type { ComponentToken as AffixComponentToken } from '../../affix/style';
import type { ComponentToken as AlertComponentToken } from '../../alert/style';
import type { ComponentToken as AnchorComponentToken } from '../../anchor/style';
import type { ComponentToken as AvatarComponentToken } from '../../avatar/style';
import type { ComponentToken as BadgeComponentToken } from '../../badge/style';
import type { ComponentToken as ButtonComponentToken } from '../../button/style';
import type { ComponentToken as CarouselComponentToken } from '../../carousel/style';
import type { ComponentToken as CheckboxComponentToken } from '../../checkbox/style';
import type { ComponentToken as CollapseComponentToken } from '../../collapse/style';
import type { ComponentToken as DescriptionsComponentToken } from '../../descriptions/style';
import type { ComponentToken as DividerComponentToken } from '../../divider/style';
import type { ComponentToken as DrawerComponentToken } from '../../drawer/style';
import type { ComponentToken as InputNumberComponentToken } from '../../input-number/style';
import type { ComponentToken as InputComponentToken } from '../../input/style';
import type { ComponentToken as PopconfirmComponentToken } from '../../popconfirm/style';
import type { ComponentToken as RadioComponentToken } from '../../radio/style';
import type { ComponentToken as SkeletonComponentToken } from '../../skeleton/style';
import type { ComponentToken as SpaceComponentToken } from '../../space/style';
import type { ComponentToken as SwitchComponentToken } from '../../switch/style';
import type { ComponentToken as TooltipComponentToken } from '../../tooltip/style';

export interface ComponentTokenMap {
  Affix?: AffixComponentToken;
  Alert?: AlertComponentToken;
  Anchor?: AnchorComponentToken;
  Avatar?: AvatarComponentToken;
  Badge?: BadgeComponentToken;
  Button?: ButtonComponentToken;
  Carousel?: CarouselComponentToken;
  Checkbox?: CheckboxComponentToken;
  Collapse?: CollapseComponentToken;
  Descriptions?: DescriptionsComponentToken;
  Divider?: DividerComponentToken;
  Drawer?: DrawerComponentToken;
  Input?: InputComponentToken;
  InputNumber?: InputNumberComponentToken;
  Popconfirm?: PopconfirmComponentToken;
  Radio?: RadioComponentToken;
  Skeleton?: SkeletonComponentToken;
  Space?: SpaceComponentToken;
  Switch?: SwitchComponentToken;
  Tooltip?: TooltipComponentToken;
}
