import type { ComponentToken as WaveToken } from '../../_util/wave/style';
import type { ComponentToken as AffixComponentToken } from '../../affix/style';
import type { ComponentToken as AlertComponentToken } from '../../alert/style';
import type { ComponentToken as AnchorComponentToken } from '../../anchor/style';
import type { ComponentToken as AppComponentToken } from '../../app/style';
import type { ComponentToken as AvatarComponentToken } from '../../avatar/style';
import type { ComponentToken as BadgeComponentToken } from '../../badge/style';
import type { ComponentToken as ButtonComponentToken } from '../../button/style';
import type { ComponentToken as CarouselComponentToken } from '../../carousel/style';
import type { ComponentToken as CheckboxComponentToken } from '../../checkbox/style';
import type { ComponentToken as CollapseComponentToken } from '../../collapse/style';
import type { ComponentToken as DescriptionsComponentToken } from '../../descriptions/style';
import type { ComponentToken as DividerComponentToken } from '../../divider/style';
import type { ComponentToken as DrawerComponentToken } from '../../drawer/style';
import type { ComponentToken as EmptyComponentToken } from '../../empty/style';
import type { ComponentToken as FlexComponentToken } from '../../flex/style';
import type { ComponentToken as FloatButtonComponentToken } from '../../float-button/style';
import type { ComponentToken as GridComponentToken } from '../../grid/style';
import type { ComponentToken as ImageComponentToken } from '../../image/style';
import type { ComponentToken as InputNumberComponentToken } from '../../input-number/style';
import type { ComponentToken as InputComponentToken } from '../../input/style';
import type { ComponentToken as LayoutComponentToken } from '../../layout/style';
import type { ComponentToken as MasonryComponentToken } from '../../masonry/style';
import type { ComponentToken as MentionsComponentToken } from '../../mentions/style';
import type { ComponentToken as MenuComponentToken } from '../../menu/style';
import type { ComponentToken as MessageComponentToken } from '../../message/style';
import type { ComponentToken as ModalComponentToken } from '../../modal/style';
import type { ComponentToken as NotificationComponentToken } from '../../notification/style';
import type { ComponentToken as PopconfirmComponentToken } from '../../popconfirm/style';
import type { ComponentToken as PopoverComponentToken } from '../../popover/style';
import type { ComponentToken as ProgressComponentToken } from '../../progress/style';
import type { ComponentToken as QRCodeComponentToken } from '../../qrcode/style';
import type { ComponentToken as RadioComponentToken } from '../../radio/style';
import type { ComponentToken as RateComponentToken } from '../../rate/style';
import type { ComponentToken as ResultComponentToken } from '../../result/style';
import type { ComponentToken as SegmentedComponentToken } from '../../segmented/style';
import type { ComponentToken as SelectComponentToken } from '../../select/style';
import type { ComponentToken as SkeletonComponentToken } from '../../skeleton/style';
import type { ComponentToken as SliderComponentToken } from '../../slider/style';
import type { ComponentToken as SpaceComponentToken } from '../../space/style';
import type { ComponentToken as SpinComponentToken } from '../../spin/style';
import type { ComponentToken as SplitterComponentToken } from '../../splitter/style';
import type { ComponentToken as StatisticComponentToken } from '../../statistic/style';
import type { ComponentToken as StepsComponentToken } from '../../steps/style';
import type { ComponentToken as SwitchComponentToken } from '../../switch/style';
import type { ComponentToken as TooltipComponentToken } from '../../tooltip/style';

export interface ComponentTokenMap {
  Affix?: AffixComponentToken;
  Alert?: AlertComponentToken;
  Anchor?: AnchorComponentToken;
  App?: AppComponentToken;
  Avatar?: AvatarComponentToken;
  Badge?: BadgeComponentToken;
  Button?: ButtonComponentToken;
  Carousel?: CarouselComponentToken;
  Checkbox?: CheckboxComponentToken;
  Collapse?: CollapseComponentToken;
  Descriptions?: DescriptionsComponentToken;
  Divider?: DividerComponentToken;
  Drawer?: DrawerComponentToken;
  Empty?: EmptyComponentToken;
  Flex?: FlexComponentToken;
  FloatButton?: FloatButtonComponentToken;
  Grid?: GridComponentToken;
  Image?: ImageComponentToken;
  Input?: InputComponentToken;
  InputNumber?: InputNumberComponentToken;
  Layout?: LayoutComponentToken;
  Masonry?: MasonryComponentToken;
  Mentions?: MentionsComponentToken;
  Menu?: MenuComponentToken;
  Message?: MessageComponentToken;
  Modal?: ModalComponentToken;
  Notification?: NotificationComponentToken;
  Popconfirm?: PopconfirmComponentToken;
  Popover?: PopoverComponentToken;
  Progress?: ProgressComponentToken;
  QRCode?: QRCodeComponentToken;
  Radio?: RadioComponentToken;
  Rate?: RateComponentToken;
  Result?: ResultComponentToken;
  Segmented?: SegmentedComponentToken;
  Select?: SelectComponentToken;
  Skeleton?: SkeletonComponentToken;
  Slider?: SliderComponentToken;
  Space?: SpaceComponentToken;
  Spin?: SpinComponentToken;
  Splitter?: SplitterComponentToken;
  Statistic?: StatisticComponentToken;
  Steps?: StepsComponentToken;
  Switch?: SwitchComponentToken;
  Tooltip?: TooltipComponentToken;
  Wave?: WaveToken;
}
